### ISSUE TITLE
Error: Cannot find module 'snappy-linux-x64-gnu'

### ISSUE THREAD

**Issue by vitorveiga** [Brooooooklyn/snappy#50] opened 2021-12-22 10:28 UTC
Hello,

I'm having an error with version 7.1.0 of snappy. 

**Steps to reproduce:**
```shell
mkdir test && cd test
npm init -y
npm i snappy@7.1.0
node -e "require('snappy')"
```
**Error:**
```js
Error: Cannot find module 'snappy-linux-x64-gnu'
Require stack:
- /tmp/node_modules/snappy/index.js
- /tmp/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/tmp/node_modules/snappy/index.js:135:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/node_modules/snappy/index.js', '/tmp/[eval]' ]
}
```
**Environment:**
* node 14.18.2
* npm 6.14.15
* Linux 5.15.10-arch1-1 x86_64 GNU/Linux

Is this a bug or I'm missing something?
Thanks

**Comment by Brooooooklyn** [comment] 2021-12-22 10:38
Oh, it's a bug caused by publishing tools. I'll yank this version and make a quick fix.

**Comment by Brooooooklyn** [comment] 2021-12-22 12:55
Closed in https://github.com/Brooooooklyn/snappy/releases/tag/v7.1.1

**Closed by Brooooooklyn** 2021-12-22 12:55 UTC
Labels: bug
